Build 9 Real World Django Projects/Proj_1_Food_Menu_App/Proj_1_Food_Menu_App/urls.py
from django.contrib import admin
from django.urls import include,path
from account import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

from account.views import registration_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/', registration_view, name='registration_view'),
    path('login/', authentication_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('accounts/profile/', user_views.profilepage,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    # /food/
    path('', views.IndexClassView.as_view(), name='index'),
    # /food/1
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('item/', views.item, name='item'),
    # add items

    path('add', views.CreateItem.as_view(), name='create_item'),
    # edit
    path('update/<int:id>/', views.update_item, name='update_item'),
    # delete
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/models.py
from django.db import models

# Create your models here.

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="")

    # delete this afterwards
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate


User = get_user_model()

class UserLogin(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user or not user.check_password(password):
                raise forms.ValidationError('Error in Login or Password')
        else:
            raise forms.ValidationError('Error in Login or Password')
        return super().clean()


class UserRegistration(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username',)

    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data['password2']
        raise forms.ValidationError('Error in password!')

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserRegistration, UserLogin
from django.contrib.auth import login, authenticate, logout


def logout_view(request):
    logout(request)
    return redirect('food:index')

def login_view(request):
    form = UserLogin(request.POST or None)
    next_get = request.GET.get('next')
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        next_post = request.POST.get('next')
        return redirect(next_get or next_post or 'food:index')

    data = {
        'form': form,
        'user_manager': user_manager,
        'user_auth': user_auth,
    }
    return render(request, 'login.html', context=data)

def registration_view(request):
    form = UserRegistration(request.POST or None)
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated

    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        data = {
            'form': form,
            'user_manager': user_manager,
            'user_auth': user_auth,
            'user': new_user,
        }
        return render(request, 'base.html', context=data)

    data = {
        'form': form,
        'user_manager': user_manager,
        'user_auth': user_auth,
    }
    return render(request, 'register.html', context=data)

@login_required
def profilepage(request):
    return render(request, 'profile.html')

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


def index(request):
    item_list = Item.objects.all()

    context = {
        'item_list': item_list,
    }
    return render(request, 'index.html', context)


class IndexClassView(ListView):
    model = Item
    template_name = 'index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('<h1>This is an item view</h1>')


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }

    return render(request, 'detail.html', context)


class FoodDetail(DetailView):
    model = Item
    template_name = 'detail.html'


#
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'item-form.html', {'form': form})


# this is a class based view for create item

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'item-form.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'item-delete.html', {'item': item})


Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/templates/login.html
{% extends 'base.html' %}

{% block body %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/templates/logout.html
{% extends 'base.html' %}

{% block body %}
  <h2>Logout</h2>
  <p>You have been logged out.</p>
{% endblock %}

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/templates/profile.html
{% extends 'base.html' %}

{% block body %}
  <h2>Profile</h2>
  <p>Welcome, {{ user.username }}!</p>
  <!-- Дополнительный контент профиля -->
{% endblock %}

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/account/templates/register.html
{% extends 'base.html' %}

{% block body %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <link rel="stylesheet" href="{% static 'food/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>

        <nav class="navbar navbar-dark bg-dark">
                <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>

                <div class="navbar">
                    <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'registration_view' %}">Registration</a>
                        <a href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </nav>
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                    {{ message }}
            </div>

            {% endfor %}
          {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row m-5">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card"/>
        </div>

        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/templates/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    </head>
<body>

    {% block body %}

    {% for item in item_list %}
        <div class="row m-5">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                Added By:<h6>{{ item.user_name }}</h6>

                <!--delete this later-->

                <!---->
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        <div class="row">
            <div class="offset-md-2 col-md-8">
                <hr>
            </div>
        </div>

    {% endfor %}
    {% endblock %}

    this is the old code


    <ul>
        <li>

            <a href=""> {{ item.id }} -- {{ item.item_name }}</a>
        </li>
    </ul>



</body>
</html>

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/templates/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

Build 9 Real World Django Projects/Proj_1_Food_Menu_App/templates/item-form.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button class="btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}